### ISSUE TITLE
Иногда в логах проскакивают ошибки.

### ISSUE THREAD

**Issue by dekosik** [voodee/web-tycoon-tools#2]
> Ошибка управления контентом { TimeoutError: waiting for selector ".externalLinkWr .baseButton:first-child" failed: timeout 30000ms exceeded
>     at new WaitTask (D:\WebTycoonBot\acc2\node_modules\puppeteer\lib\DOMWorld.js:554:28)
>     at DOMWorld._waitForSelectorOrXPath (D:\WebTycoonBot\acc2\node_modules\puppeteer\lib\DOMWorld.js:483:22)
>     at DOMWorld.waitForSelector (D:\WebTycoonBot\acc2\node_modules\puppeteer\lib\DOMWorld.js:437:17)
>     at Frame.waitForSelector (D:\WebTycoonBot\acc2\node_modules\puppeteer\lib\FrameManager.js:606:47)
>     at Frame.<anonymous> (D:\WebTycoonBot\acc2\node_modules\puppeteer\lib\helper.js:109:23)
>     at Page.waitForSelector (D:\WebTycoonBot\acc2\node_modules\puppeteer\lib\Page.js:1073:29)
>     at module.exports (D:\WebTycoonBot\acc2\libs\tasks\make\content.js:61:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

> Ошибка при управление работниками { TimeoutError: waiting for selector ".grid" failed: timeout 30000ms exceeded
>     at new WaitTask (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\DOMWorld.js:554:28)
>     at DOMWorld._waitForSelectorOrXPath (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\DOMWorld.js:483:22)
>     at DOMWorld.waitForSelector (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\DOMWorld.js:437:17)
>     at Frame.waitForSelector (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\FrameManager.js:606:47)
>     at Frame.<anonymous> (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\helper.js:109:23)
>     at Page.waitForSelector (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\Page.js:1073:29)
>     at module.exports (D:\WebTycoonBot\acc4\libs\workers\index.js:36:18)
>     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

**Comment by dekosik** [comment]
> Ошибка управления сайтом chrome-error://chromewebdata/ { TimeoutError: waiting for selector ".prevNextNavGroup .leftArrow" failed: timeout 30000ms exceeded
>     at new WaitTask (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\DOMWorld.js:554:28)
>     at DOMWorld._waitForSelectorOrXPath (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\DOMWorld.js:483:22)
>     at DOMWorld.waitForSelector (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\DOMWorld.js:437:17)
>     at Frame.waitForSelector (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\FrameManager.js:606:47)
>     at Frame.<anonymous> (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\helper.js:109:23)
>     at Page.waitForSelector (D:\WebTycoonBot\acc4\node_modules\puppeteer\lib\Page.js:1073:29)
>     at module.exports (D:\WebTycoonBot\acc4\libs\tasks\make\index.js:41:18) name: 'TimeoutError' }
